# Generated by Django 4.2.1 on 2025-03-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='actual',
            field=models.BooleanField(choices=[(0, 'Старая'), (1, 'Актуальная')], default=0),
        ),
    ]
