# Generated by Django 5.1.7 on 2025-05-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'Видна всем'), (2, 'Только авторизованным'), (3, 'Только авторам и администраторам')], default=1, verbose_name='Видимость'),
        ),
    ]
