# Generated by Django 5.1.7 on 2025-06-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_commentvote_newsvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='visibility',
        ),
    ]
